Publish instructions for keypresses in the keyboard_controller.
FlaSpaceInst/EZ-RASSOR pull request #355
Opened 2020-08-20 02:28 UTC by tgsachse

2020-08-20 17:59 UTC, CSharpRon commented on packages/communication/ezrassor_keyboard_controller/launch/keyboard_controller.launch
> +  <arg name="rear_arm_instructions_topic"/>
I think you should go back to using "back". The ezrassor_sim_control refers to the arms and drums by front and back.

2020-08-20 18:00 UTC, CSharpRon commented on packages/communication/ezrassor_keyboard_controller/nodes/keyboard_controller
> +REAR_ARM_UP_INSTRUCTION = std_msgs.msg.Float32(1.0)
Again  **back** would probably be a good choice for consistency [see ezrassor_sim_control/config]

2020-08-20 18:01 UTC, CSharpRon requested changes
Clean changes! There was only one change I pointed out: using back instead of rear for consistency.

2020-08-20 18:05 UTC, tgsachse commented on packages/communication/ezrassor_keyboard_controller/nodes/keyboard_controller
> +REAR_ARM_UP_INSTRUCTION = std_msgs.msg.Float32(1.0)
Yeah I was leaning towards swapping out "back" to "rear" everywhere, but I don't actually remember why I preferred that. Doesn't really matter one way or the other, I'll change everything back to "back" :)

2020-08-21 02:24 UTC, CSharpRon approved these changes
Approve!

2020-08-21 03:28 UTC, merged