Delayed teleop
FlaSpaceInst/EZ-RASSOR pull request #368
Opened 2020-09-01 03:53 UTC by CSharpRon

Applies to #350 

Two new packages have been added:
- actions/ezrassor_teleop_actions (Holds the logic for the action client and action server)
- messages/ezrassor_teleop_msgs (Holds the .action specification that ROS builds to determine the data types for goal, feedback, and result)

The action server node starts with the configurable_simulation.launch file. The client must be executed manually and will exit early if a text file containing instructions is not provided. Example:
```sh
cd packages/actions/ezrassor_teleop_actions/scripts
python teleop_action_server.py actions.txt
```

One thing to note: The dig and dump functionality only applies to the front drum at this time.

2020-09-02 16:16 UTC, tigressine requested changes
Overall great work man, this looks good. I left a lot of comments but am open to discuss any of them.

Overall comments:
- I know I said I was down with a new /actions superpackage, but now I'm thinking this is probably better suited to be in the /communication superpackage.
- I know you said best practice was to separate the msgs and the impl into two packages. Is this entirely necessary? I don't think autonomy does it for their msgs (although that could be an oversight). Could you link me the article/wiki/whatever that describes this? I'm 50/50, but if we don't need another github repo to maintain and bloomify in the future that's a plus.
- I'm wondering if the overall name of the package can be improved. Would prefer to leave the word actions out of any customer facing names, since we don't necessarily need to expose the implementation to them. I think it's an opportunity to come up with a fun or creative name, or maybe something descriptive but less fun like `ezrassor_instruction_processor` or something, idk. Maybe the name is fine idk. :P
- I'll take a look at that issue with the tests real quick and will add a commit if I can fix it. EDIT: Fixed it, problem was the docker script never sourced the `devel/setup.sh`. No clue why this worked before, pretty weird. I also updated the script to install the software instead of only building it, and then I source the installation. Tests pass now.
- Could we squash and rebase these commits like I described yesterday? It doesn't have to be one big commit, you can decide what's best, but I think it should probably be cleaned up compared to what it is now. You'll be able to `git push --force` and it'll update this PR. EDIT: after skimming the commit msgs it can probably all be one commit. Don't need separate commits for formatting for example, code should already be properly formatted each commit.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
Can we ditch the autogenerated comments in this file and change the indentation to 2 spaces to match other CMakeLists in the project?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/package.xml
> +  <!-- The export tag contains other, unspecified, tags -->
Can remove the entire <export> block and the "Other tools" comment.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/package.xml
> +  <build_export_depend>roscpp</build_export_depend>
Do we need roscpp for this?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/package.xml
> +
Can you add your name as an <author> tag as well?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/actions.txt
> +# Move Commands
Is this like a sample? Or a leftover file?

If you want to document how this node works and the command format I'd request we do that in the wiki under a new node page.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            "/teleop_action_server", TeleopAction
Is this the topic you publish the actions to? Can it be parameterized?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        self._ac = actionlib.SimpleActionClient(
Not usually a fan of acronym names, maybe just `_client`.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            rospy.loginfo("{} has been sent.".format(direction))
You don't need to explicitly format the string in log msgs, the logger will do that for you. Not sure if it understands the newer `{}` syntax but this example is from the ROS logging tutorial:
```
rospy.logerr("%s returned the invalid value %s", other_name, other_value)
```

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +                rospy.logwarn("HOUSTON, WE HAVE A PROBLEM")
;)

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        rospy.loginfo(feedback)
I'm a pretty sparse logger, but if you feel like these msgs provide real value that's fine. Note you might be able to condense using the syntax I showed above.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        rospy.loginfo(feedback)
micronit: `Status :` vs `Result: `, should pick a spacing with the colon.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            success = self._ac.wait_for_result(rospy.Duration(duration + 2.0))
What's the magic `2.0` for? Maybe turn into a constant?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +def read_instructions(file):
Looks like there's no validation on the file, what happens if the 4th instruction is spelled wrong or the number they include is a float? It won't fail fast, it will process the first three instructions and then spin out.

I'd recommend trying to return a list of TeleopGoals from `read_instructions`, but make sure each TeleopGoal is valid. Maybe rosactions supports using an enum type thing for `direction`? Ideally if the file is invalid we would fail in this function, not later in the code.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        print("Please provide a file to the client script...")
Shouldn't use `print()` anywhere really, should only use log statements.

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +    print("Actions completed. Closing client...")
So this is effectively a 1-off script. The user experience is:

- Run the system via our launch files
- Write your instruction file
- Call `rosrun ezrassor_teleop_actions teleop_action_client my-instruction-file`
- Watch robot go burrr

Seems good to me, just confirming the strategy. Have you tried importing this lib into an interpreter and calling the client that way? Code is pretty well separated, you might be able to.

e.g.

```
$ python

import lib

client = lib.Client()
actions = [
   Action("Do Thing", 5),
   Action("Another Thing", 10),
]

client.send_movement_goal(actions)
```

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        self._as = actionlib.SimpleActionServer(
`_server` ?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            "/teleop_action_server",
Parameterize?

2020-09-02 16:16 UTC, tigressine commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            "front_drum_instructions", Float32, queue_size=1
parameterize?

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        return euler[2]
This is a great example as to why we need a EZRASSOR lib that wraps all this state for all our other nodes to use so we don't have to dup code like this.

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            self._as.set_aborted(result)  # Returns failure
Nit: inline comments are bleh

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            time.sleep(1)
Constantify?

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +    rospy.init_node("teleop_action_server")
Constantify?

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            self._as.set_aborted(result)  # Returns failure
nit: inline comments

2020-09-02 16:16 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        result.y = self.y
So the x/y position is only required for the feedback? I wonder if we could reduce the feedback msg to not include this for now (maybe it just returns false if not done, true if done). This is obviously less useful but we don't have a usecase for intermediate x/y positions right? And returning these x/y positions forces us to copy a bunch of code + depend directly on the simulation and gazebo link states.

Might be better to keep it simple for now, then add this usecase in later if the need for it arises, plus by then we will have a controller library and wont need to copy code or depend on gazebo topics.

2020-09-02 16:16 UTC, tgsachse commented on packages/extras/ezrassor_launcher/launch/configurable_simulation.launch
> +    <include file="$(find ezrassor_teleop_actions)/launch/teleop_action_server.launch"/>
Shouldn't this be in configurable_communication? I feel like this is part of the comms system and doesnt need to sim up to work (assuming we drop the link state dependency). I'd strongly prefer this was wired in configurable_communication and togglable with a new `control_method` e.g. `control_methods:="keyboard autonomy actions"` (or whatever u want to call it)

2020-09-02 16:16 UTC, tgsachse commented on packages/messages/ezrassor_teleop_msgs/CMakeLists.txt
> +## is used, also find other catkin packages
Can we drop all the generated comments?

2020-09-02 16:16 UTC, tgsachse commented on packages/messages/ezrassor_teleop_msgs/CMakeLists.txt
> +  roscpp
Do you depend on roscpp here to be able to compile the msgs for C++? If so that's fine.

2020-09-02 16:16 UTC, tgsachse commented on packages/messages/ezrassor_teleop_msgs/package.xml
> +
Add author tag?

2020-09-02 16:16 UTC, tgsachse commented on packages/messages/ezrassor_teleop_msgs/package.xml
> +    <!-- Other tools can request additional information be placed here -->
Can remove

2020-09-05 15:34 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        return euler[2]
Facts

2020-09-05 15:38 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        result.y = self.y
I would say that it is beneficially and should stay. Current position data is valuable to operators and the data can even be plotted for analysis or replay. For example you can see if drift is occurring. 

Ultimately it makes the feedback part of this realistic and usable instead of just a True/False flag for completion which is implied anyways.

2020-09-05 17:59 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
Fixed!

2020-09-05 17:59 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/package.xml
> +  <!-- The export tag contains other, unspecified, tags -->
Fixed!

2020-09-05 18:00 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/package.xml
> +  <build_export_depend>roscpp</build_export_depend>
Nope, fixed!

2020-09-05 18:00 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/package.xml
> +
Fixed!

2020-09-05 18:00 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/actions.txt
> +# Move Commands
Good call, I removed it from the project.

2020-09-05 18:01 UTC, CSharpRon commented on packages/extras/ezrassor_launcher/launch/configurable_simulation.launch
> +    <include file="$(find ezrassor_teleop_actions)/launch/teleop_action_server.launch"/>
I added a check for actions. So the server only launches when actions is passed in. However, right now the code is tightly coupled with the simulation. Until that changes, it makes the most sense to keep it in configurable_simulation.launch

2020-09-05 18:01 UTC, CSharpRon commented on packages/messages/ezrassor_teleop_msgs/CMakeLists.txt
> +## is used, also find other catkin packages
Fixed!

2020-09-05 18:01 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        self._ac = actionlib.SimpleActionClient(
Fixed!

2020-09-05 18:03 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            "/teleop_action_server", TeleopAction
What is the benefit of parameterization? If we were reusing this all over the place then I could understand but parameterizing it would add unnecessary abstraction here. It is frustrating to have to "figure out" where the value is coming from when it really doesn't change. See the autonomy package and the parameterized topic names. They don't change but when you look at the autonomy scripts, you have to do a search on all of the project files for the parameter name to see where they are set. 

Hopefully that defense makes sense. Basically I am saying that it is unnecessary since we don't have a use case for reuse.

2020-09-05 18:04 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            rospy.loginfo("{} has been sent.".format(direction))
Good call, fixed!

2020-09-05 18:04 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        rospy.loginfo(feedback)
Good find, fixed!

2020-09-05 18:04 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            success = self._ac.wait_for_result(rospy.Duration(duration + 2.0))
This value is only used once so turning it into a constant just adds another step for the developer to interpret the value. Here explicit value is fine.

2020-09-05 18:06 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            success = self._ac.wait_for_result(rospy.Duration(duration + 2.0))
It's not really a magic number though, I just decided to add a buffer just in case the processor stutters for example (since the simulation runs differently according to your machine).

2020-09-05 18:06 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +def read_instructions(file):
You are 100% right and I just added a validate() function for this purpose.

2020-09-05 18:07 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +        print("Please provide a file to the client script...")
True, bad habit :) I fixed it by using rospy.logerr

2020-09-05 18:09 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +    print("Actions completed. Closing client...")
Correct and correct! I tried running it through the interpreter and it worked perfectly. 
```py
from teleop_action_client import TeleopActionClient

client = TeleopActionClient()
actions = ["forward 5", "backward 5"]

client.validate(actions)
client.send_movement_goal(actions)
```

2020-09-05 18:09 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        self._as = actionlib.SimpleActionServer(
Fixed!

2020-09-05 18:10 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            "front_drum_instructions", Float32, queue_size=1
See my previous comment on parameters

2020-09-05 18:10 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            "/teleop_action_server",
See my previous comment on parameters

2020-09-05 18:10 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            self._as.set_aborted(result)  # Returns failure
You're right, I fixed it

2020-09-05 18:11 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +    rospy.init_node("teleop_action_server")
Don't see a need to, but it ties into my previous comments.

2020-09-05 18:11 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +            self._as.set_aborted(result)  # Returns failure
Fixed!

2020-09-05 18:11 UTC, CSharpRon commented on packages/messages/ezrassor_teleop_msgs/CMakeLists.txt
> +  roscpp
Negative, fixed!

2020-09-05 18:11 UTC, CSharpRon commented on packages/messages/ezrassor_teleop_msgs/package.xml
> +
Fixed!

2020-09-05 18:11 UTC, CSharpRon commented on packages/messages/ezrassor_teleop_msgs/package.xml
> +    <!-- Other tools can request additional information be placed here -->
Fixed!

2020-09-06 21:57 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            "/teleop_action_server", TeleopAction
There are two reasons this is important:

1) When it is hardcoded like this, the topic is always global, which prevents us from running multiple robots at once. They'd both listen to the same topic and so they couldn't be controlled independently. With the other manual control methods, we pull in the namespace of the robot into the topic name so that we can have "/ezrassor1/wheel_instructions" and "/ezrassor2/wheel_instructions" etc.

2) When we control the robot manually and have no autonomous component, we don't launch the topic switches and we publish our manual instructions directly to "/ezrassorX/wheel_instructions". When we do have an autonomous component, we publish to "ezrassorX/manual_wheel_instructions" and then the topic switch switches back and forth between autonomy and manual control.

This is functionality that can be added later once we abstract the simulation away more fully (remove reliance on sim in autonomy) so we can fix later, but I'd still say this is technical debt. Will ship for now.

2020-09-06 22:14 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            success = self._ac.wait_for_result(rospy.Duration(duration + 2.0))
I guess I just prefer to have these numbers have names, if it was called "buffer" then I wouldn't wonder what it is for. Maybe it's actually to offset some value, or maybe duration can't be below X and so this number ensures it never is, or maybe it's just arbitrary buffer. Hard to tell when it's the raw number without a name, but I see your point, fine with leaving it for now if you disagree.

2020-09-06 22:15 UTC, tgsachse commented on packages/actions/ezrassor_teleop_actions/source/ezrassor_teleop_actions/teleop_action_server.py
> +        result.y = self.y
This is fine for now, I see your point. Will prioritize creating the publishing/monitoring lib once we get multi-repo ros2.

2020-09-06 23:28 UTC, tgsachse approved these changes

2020-09-07 00:35 UTC, CSharpRon commented on packages/actions/ezrassor_teleop_actions/scripts/teleop_action_client.py
> +            success = self._ac.wait_for_result(rospy.Duration(duration + 2.0))
I added a line comment above after your review for clarity

2020-09-07 00:37 UTC, merged