Added WSL instructions txt
FlaSpaceInst/EZ-RASSOR pull request #398
Opened 2020-11-16 19:43 UTC by ffermo

Added instructions txt file under /docs/ and added a line in the README to hyperlink to txt file.

2020-11-16 19:48 UTC, ffermo commented
@tgsachse for review.

2020-11-17 06:09 UTC, tgsachse requested changes
Nice instructions! Had one ask regarding organization, thanks for doing this :)

2020-11-17 06:09 UTC, tgsachse commented on docs/WINDOWSINSTALL.txt
> +This is working for Windows 10 version 1909. You can verify which Windows version you are on by using keyboard shortcut WIN + r and typing 'winver'.
Would rather this was part of the readme where the other installation instructions are.

- Could you add a new section after Customized Installation, perhaps called WSL Configuration or something
- In this section, include all of the parts of 1)
- Next, create a step where you tell users to follow the instructions in Typical Installation (we don't want to repeat instructions here and in typical installation for installing ROS/EZ-RASSOR repository, and we also don't want to include the instructions to install ROS at all bc they are the most up to date on the ros wiki, no point in maintaining them on our side (and possibly having out of date info)).
- Add section 6)
- Drop the test instructions (testing is covered in the readme already)

2020-11-17 21:37 UTC, ffermo commented on docs/WINDOWSINSTALL.txt
> +This is working for Windows 10 version 1909. You can verify which Windows version you are on by using keyboard shortcut WIN + r and typing 'winver'.
Changes made! Feel free to modify or request any other changes.

2020-11-18 18:58 UTC, tgsachse approved these changes
Great work and nice attention to detail.

2020-11-19 00:23 UTC, merged